### PR TITLE
I mean this file

### PR DESCRIPTION
**Pull request by mishin**
to increase the kwalitee in param "has known license in source file"
according to http://cpants.cpanauthors.org/author/yves and http://cpants.cpanauthors.org/kwalitee

### CODE REVIEW

**Comment by demerphq** [comment]
Hrm. I see Ivans point, but I wonder, do we really want people using different licenses for different languages? The Perl Artistic license is pretty loose....

**Comment by ikruglov** [comment]
Since we have different authors it should be up to the people IMO.

**Comment by dgryski** [comment]
The Go community for the most part uses Apache, because that's what the Go project itself uses.  i just noticed I never got around to adding one for the Go version.  I'll fix that.

**Comment by demerphq** [comment]
On 29 April 2015 at 14:56, Ivan Kruglov <notifications@github.com> wrote:

> Since we have different authors it should be up to the people IMO.
>
>
>
Im not sure that is a good reason. By that token the linux project would
have hundreds of licenses.

Also there is a problem here with having different code under different
license in the same repo.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by dgryski** [comment]
All the contributors to the Go port are Booking developers, and all the work by developers other than @ikruglov and myself was done on Booking-time during hackathons.  We can justifiably say that Booking.com owns that code and "we" (whatever that means) can chose the license we want on it.

For the Ruby and Python ports, the developers are *now* working for Booking (although they weren't when the ports were started.)  But they're easy enough to ask.

There is still the issue of the non-Booking.com contributions, which (luckily?) are only a few small patches.

**Comment by dgryski** [comment]
And note this is beginning to duplicate https://github.com/Sereal/Sereal/issues/63

**Comment by manzur** [comment]
Note from a stranger:
Sereal positions itself as data exchange format between different languages and platforms. So by having separate licences with different limitations we're losing one of the main advantages of the project itself. Moreover, it doesn't buy anything for the project except complicating the life of a user. IMHO, it's better to have one licence that allows it to be used easily from Perl, Go, Ruby and etc.

**Pull request merged**
