### PR TITLE
[Java] Bump jackson-databind 2.13.4.1 to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by akh1lt**
- Split jackson-databind and jackson-core as there are versioning discrepencies in maven repository

### CODE REVIEW

**Comment by akh1lt** [comment]
@demerphq I don't think I have merge perms. Feel free top merge it when you get time.

**Comment by demerphq** [comment]
Huh. Ill see what perms I need to give you. Anyway, merged.

**Comment by demerphq** [comment]
and thanks!

**Comment by akh1lt** [comment]
No worries Yves. Happy to contribute.

**Pull request merged**
